### ISSUE TITLE
Resize does not use source rectangle x/y values

### ISSUE THREAD

**Issue by SepiaGroup** [JimBobSquarePants/ImageSharp#118]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

If you have a source image of 100x100 and do 

image.Resize(width, height, sampler, sourceRec, destRec)

where 

sourceRec = new Rectangle(0, 0, 100, 100) 
destRec = new Rectangle (0, 0, 100, 100) 

you get a copy of the image - this works correctly

but if you  have 

sourceRec = new Rectangle(0, 10, 100, 90) 
destRec = new Rectangle (0, 0, 100, 100) 

i would expect the source rectangle to start 10 pixels down the image and go for 90 pixels.

what i see is the rectangle starts at 0 and goes for 90 pixels.

the destination rectangle seems to work correctly when you set the x/y values.

### System Configuration

- ImageSharp version:
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by JimBobSquarePants** [comment]
Should be fixed now.

**Comment by agr** [comment]
I still see it on the current version: 1.0.0-alpha7-00016.

Tested against an [image](http://i.imgur.com/d7qngZD.png) with the following code:
            var img = Image.Load(@"C:\...\Downloads\cross.png");
            var destRect = new Rectangle(0, 0, 100, 100);
            var sourceRect = new Rectangle(490, 490, 20, 20);
            img.Resize(100, 100, new BicubicResampler(), sourceRect, destRect)
                .SaveAsJpeg(File.OpenWrite(@"C:\...\Downloads\cross2.jpg"));

Expected output is the cross from the center of the image, actual - diagonal line from the top left corner.

**Comment by JimBobSquarePants** [comment]
Thanks for adding demo code there @agr 

It was a regression due to changes during optimization. If you give it 10 minutes there should be a new working build available. 

Cheers

James

**Comment by agr** [comment]
Thanks!

**Comment by antonfirsov** [comment]
Ehh sorry, my fault again 😅 
Thanks for fixing it @JimBobSquarePants!
